### ISSUE TITLE
Running commands before/after the microk8s cluster deployment with Openstack provider

### ISSUE THREAD

**Issue by Fevereiro6** [canonical/cluster-api-control-plane-provider-microk8s#34]
Can we run commands before and/or after deploying the microk8s cluster in the openstack provider? It would be preferable , if this was possible using the cluster generated YAML.

**Comment by sachinkumarsingh092** [comment]
Closing this and continuing this discussion in https://github.com/canonical/cluster-api-bootstrap-provider-microk8s/issues/60
