### ISSUE TITLE
upgrade-pod keep restarting even though node is successfully upgraded

### ISSUE THREAD

**Issue by Kun483** [canonical/cluster-api-control-plane-provider-microk8s#72]
**What steps did you take and what happened:**
I deployed a 3 CP 2 Workers cluster in v1.27. Then I triggered the `InPlaceUpgrade`. `upgrade-pod` pod is created in the default namespace of the 1st CP node. Then, this CP node is successfully upgraded to v1.28, and then the corresponding machine got upgraded as well. However, after that, `upgrade-pod` got stuck in `CrashLoopBackOff` -> `completed` -> `CrashLoopBackOff` with more than 20 restarts. When describing `upgrade-pod`, it gives me the error below:
```
Type     Reason   Age                  From     Message
----     ------   ----                 ----     -------
Warning  BackOff  84s (x347 over 76m) kubelet  Back-off restarting failed container upgrade in pod upgrade-pod_default
```
logs show:
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   200  100   155  100    45   1393    404 --:--:-- --:--:-- --:--:--  1801
Stream closed EOF for default/upgrade-pod (upgrade)
```
**What did you expect to happen:**
After the first CP node got upgraded to the desired version, `upgrade-pod` should be deleted from that CP node and re-deployed to the next node. 

**Anything else you would like to add:**
I think the code for deleting upgrade-pod never got executed during 1InPlaceUpgrade1. [cluster-api-control-plane-provider-microk8s/controllers/reconcile.go at ac3d9e3e8da1b9eb9db0424e355018e4b8faa1b6 · canonical/cluster-api-control-plane-provider-microk8s](https://github.com/canonical/cluster-api-control-plane-provider-microk8s/blob/ac3d9e3e8da1b9eb9db0424e355018e4b8faa1b6/controllers/reconcile.go#L244-L250)
```
1.7297246802853289e+09	INFO	Waiting for upgrade node to be updated to the given version...	{"controller": "microk8scontrolplane", "controllerGroup": "controlplane.cluster.x-k8s.io", "controllerKind": "MicroK8sControlPlane"}
1.7297246902987778e+09	INFO	Now updating machine kun-microk8s-cp-9vfgb version to v1.28.0...	{"controller": "microk8scontrolplane", "controllerGroup": "controlplane.cluster.x-k8s.io", "controllerKind": "MicroK8sControlPlane"}
1.7297247003208792e+09	INFO	attempting to set control plane status	{"controller": "microk8scontrolplane", "controllerGroup": "controlplane.cluster.x-k8s.io", "controllerKind": "MicroK8sControlPlane"}
1.7297247003444061e+09	INFO	ready replicas	{"controller": "microk8scontrolplane", "controllerGroup": "controlplane.cluster.x-k8s.io", "controllerKind": "MicroK8sControlPlane"}
1.7297247003566322e+09	INFO	successfully updated control plane status	{"controller": "microk8scontrolplane", "controllerGroup": "controlplane.cluster.x-k8s.io", "controllerKind": "MicroK8sControlPlane"}
1.729724700356677e+09	INFO	Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference	{"controller": "microk8scontrolplane", "controllerGroup": "controlplane.cluster.x-k8s.io", "controllerKind": "MicroK8sControlPlane"}
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x146c42e]
```

**Env:**
**MicroK8s Control Plane and Bootstrap provider:** v0.6.10
**Upgrade** from v1.27 to v.1.28
**Infra**: MaaS bare Metal for both CP and worker nodes
**OS**: Ubuntu
**UpgradeStrategy**: InPlaceUpgrade

**Comment by HomayoonAlimohammadi** [comment]
Hi @Kun483! Thanks for reporting this. May I ask for a broader scope of logs from the control plane provider? We'll start looking into this and report any further findings here.

**Comment by sadysnaat** [comment]
@HomayoonAlimohammadi I think you should be checking the logs from pod named `upgrade-pod` and not `upgrade` pod. As the former is created by canonical for inPlace upgrade https://github.com/canonical/cluster-api-control-plane-provider-microk8s/blob/14d99000a4a26139a2f6ea7e4aa8622907177125/controllers/reconcile.go#L700. `upgrade` pod is internal to SpectroCloud. 

Please let me know if any help is needed to get the correct pod logs.

**Comment by HomayoonAlimohammadi** [comment]
@sadysnaat Thanks for correcting me. You're right. I'm going to try to reproduce this issue.

**Comment by JPedro2** [comment]
@HomayoonAlimohammadi Our environment is fully airgapped and with a total of 5 bare-metal nodes, no LXD involved. Also with `disableDefaultCNI=true` and Cilium v1.15.3 installed as a helm-chart. Can you please test under the same conditions?

Below are the microk8s pre-loaded images and Pre/PostRun commands that we use under the same environment:
```
tracking:     1.28/stable
channels:
  1.28/stable:    v1.28.14 2024-09-24 (7231) 186MB classic

images:
  - image: docker.io/cdkbot/hostpath-provisioner:1.4.2
  - image: docker.io/coredns/coredns:1.10.1
  - image: docker.io/busybox:1.28.4
  - image: registry.k8s.io/metrics-server/metrics-server:v0.6.3
  - image: registry.k8s.io/pause:3.7
  - image: docker.io/curlimages/curl:7.87.0
```

```
microk8sConfig:
  addons:
    - dns
  upgradeStrategy: InPlaceUpgrade
  snapstoreProxyScheme: "https"
  snapstoreProxyDomain: "<redacted>"
  snapstoreProxyId: "<redacted>"
  preRunCommands:
    - |
      # import certificate if using snap store proxy with https and using private CA/cert
      cat > /usr/local/share/ca-certificates/pcr_ca.crt << EOF
      -----BEGIN CERTIFICATE-----
      <redacted>
      -----END CERTIFICATE-----
      EOF
      sudo update-ca-certificates

  postRunCommands:
    - |
      mkdir -p /var/snap/microk8s/current/args/certs.d/custom_ca
      cat > /var/snap/microk8s/current/args/certs.d/custom_ca/ca.crt << EOF
      -----BEGIN CERTIFICATE-----
      <redacted>
      -----END CERTIFICATE-----
      EOF

      # create registry mirror for docker.io
      cat <<EOF > /var/snap/microk8s/current/args/certs.d/docker.io/hosts.toml
      server = "<redacted>"
      [host."<redacted>"]
      capabilities = ["pull", "resolve"]
      override_path = true
      ca = "/var/snap/microk8s/current/args/certs.d/custom_ca/ca.crt"
      EOF

      # Repeat this for each additional registry. No need to create each file specifying its content, this will be cleaner
      # Create registry mirror for gcr.io
      mkdir -p /var/snap/microk8s/current/args/certs.d/gcr.io/
      cp /var/snap/microk8s/current/args/certs.d/docker.io/hosts.toml /var/snap/microk8s/current/args/certs.d/gcr.io/hosts.toml

      # create registry mirror for ghcr.io
      mkdir -p /var/snap/microk8s/current/args/certs.d/ghcr.io/
      cp /var/snap/microk8s/current/args/certs.d/docker.io/hosts.toml /var/snap/microk8s/current/args/certs.d/ghcr.io/hosts.toml

      # Create registry mirror for k8s.gcr.io
      mkdir -p /var/snap/microk8s/current/args/certs.d/k8s.gcr.io/
      cp /var/snap/microk8s/current/args/certs.d/docker.io/hosts.toml /var/snap/microk8s/current/args/certs.d/k8s.gcr.io/hosts.toml

      # Create registry mirror for registry.k8s.io
      mkdir -p /var/snap/microk8s/current/args/certs.d/registry.k8s.io/
      cp /var/snap/microk8s/current/args/certs.d/docker.io/hosts.toml /var/snap/microk8s/current/args/certs.d/registry.k8s.io/hosts.toml

      # Create registry mirror for quay.io
      mkdir -p /var/snap/microk8s/current/args/certs.d/quay.io/
      cp /var/snap/microk8s/current/args/certs.d/docker.io/hosts.toml /var/snap/microk8s/current/args/certs.d/quay.io/hosts.toml
```

**Comment by Kun483** [comment]
@HomayoonAlimohammadi 
This is AWS InPlaceUpgrade for 1 CP cluster, which will make `upgrade-pod` keep restarting.
[aws_inplace.txt](https://github.com/user-attachments/files/17510703/aws_inplace.txt)

**Comment by HomayoonAlimohammadi** [comment]
@Kun483 Thanks for attaching the logs. Looks like not handling an already created `upgrade-pod` is an issue on our side which we'll start working towards a fix for. But the crash loop issue of the `upgrade-pod` does not seem to be exactly related to our CAPI controllers. WDYT?
The `upgrade-pod` only runs a simple curl: https://github.com/canonical/cluster-api-control-plane-provider-microk8s/blob/main/controllers/reconcile.go#L714

**Comment by HomayoonAlimohammadi** [comment]
@Kun483 Would you please provide me with more info/logs of the `upgrade-pod`? Maybe using `--previous`?
I'll let you know when the "not handling already created `upgrade-pod`" issue is fixed.

**Comment by Kun483** [comment]
```
➜  Downloads kubectl logs upgrade-pod --previous
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   200  100   155  100    45    192     55 --:--:-- --:--:-- --:--:--   247
{"type":"error","status-code":400,"status":"Bad Request","result":{"message":"snap has no updates available","kind":"snap-no-update-available","value":""}}
```

**Comment by Kun483** [comment]
@HomayoonAlimohammadi Thanks in advance! I want to share another error regarding the HA cluster InPlaceUpgrade in MaaS. 

**Observations**: When triggered the InPlaceUpgrade, `upgrade-pod` is scheduled in the 1st CP node, then API server will be temporarily down. `connect: connection refused`. Then, it will upgrade node version and machine version. After that, however, removing upgrade-pod will result in `nil pointer dereference` error. Then, in next reconcile of `microk8s-control-plane-controller-manager`, it will only check if the first-created machine the same major and minor version as MCP. It won't check the other machines' version. Also, it won't delete `upgrade-pod` on the first-created node.

[maas_HA_Inplace_new.txt](https://github.com/user-attachments/files/17547986/maas_HA_Inplace_new.txt)

Logs of `upgrade-pod` still show upgrade is successful: 
```
➜  Downloads k logs upgrade-pod --previous
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   200  100   155  100    45   1463    424 --:--:-- --:--:-- --:--:--  1904
{"type":"error","status-code":400,"status":"Bad Request","result":{"message":"snap has no updates available","kind":"snap-no-update-available","value":""}}%
```
